// Converts raw document text (extracted from a PDF or pasted) into structured
// financial records.
//
// Two strategies, tried in order:
//   1. LLM extraction (OpenAI JSON mode) — robust for arbitrary statement
//      layouts. Used when OPENAI_API_KEY is set.
//   2. Heuristic label/number extraction — a dependency-free fallback so the
//      pipeline still produces something to verify when no LLM is available.
//
// Because PDF extraction is never perfect, the upload page always shows the
// result in an editable table for the user to confirm before analysis.

import type { FinancialRecordInput } from "./types";
import { extractFinancialsWithLlm } from "./llm";
import { reconcileRecords } from "./reconcile";

export type ExtractionMethod = "pdf-llm" | "pdf-heuristic" | "csv" | "xlsx";
export type ExtractionConfidence = "high" | "medium" | "low";

export interface ExtractionResult {
  records: FinancialRecordInput[];
  warnings: string[];
  method: ExtractionMethod;
  confidence: ExtractionConfidence;
  companyName: string | null;
  currency: string | null;
}

// Field label aliases used by the heuristic scanner. Patterns are tried in
// PRIORITY order (first match wins), so "Total ..." subtotal lines are listed
// before the section headers / component lines they summarise. This is what
// lets the parser pick "Total net sales 143,756" over the "Net sales:" header.
const LINE_ITEM_ALIASES: Array<{
  field: keyof Omit<FinancialRecordInput, "year">;
  patterns: RegExp[];
}> = [
  {
    field: "costOfGoodsSold",
    patterns: [
      /total cost of sales/i,
      /total cost of revenue/i,
      /cost of goods sold/i,
      /cost of sales/i,
      /cost of revenue/i,
      /\bcogs\b/i,
    ],
  },
  {
    field: "operatingCashFlow",
    // The lookahead (label immediately followed by a figure) skips the
    // "Adjustments to reconcile net income to cash generated by operating
    // activities:" subheader and matches only the total line.
    patterns: [
      /cash generated by operating activities(?=\s*:?\s*\$?\s*[\d(])/i,
      /net cash (?:generated|provided)(?: by)? operating activities(?=\s*:?\s*\$?\s*[\d(])/i,
      /net cash (?:from|provided by|used in) operating activities(?=\s*:?\s*\$?\s*[\d(])/i,
      /net cash (?:from|provided by|used in) operating/i,
      /cash (?:flow )?from operations/i,
      /operating cash flow/i,
      /\bocf\b/i,
    ],
  },
  {
    field: "revenue",
    patterns: [
      /total net sales/i,
      /total revenue/i,
      /total sales/i,
      /net sales/i,
      /\brevenue\b/i,
      /\bturnover\b/i,
    ],
  },
  {
    field: "netIncome",
    patterns: [
      /net income/i,
      /net profit/i,
      /profit for the (?:year|period)/i,
      /(?:profit|loss) after tax/i,
      /net earnings/i,
    ],
  },
  {
    field: "totalAssets",
    patterns: [/total assets/i],
  },
  {
    field: "totalLiabilities",
    patterns: [/total liabilities/i],
  },
  {
    field: "equity",
    patterns: [
      /total (?:shareholders|stockholders|owners)['’]? equity/i,
      /total equity/i,
      /shareholders['’]? equity/i,
    ],
  },
  {
    field: "cash",
    patterns: [/cash and cash equivalents/i, /cash (?:&|and) equivalents/i, /\bcash\b/i],
  },
  {
    field: "receivables",
    // "accounts receivable" first; the trade-receivables pattern guards against
    // "Vendor NON-trade receivables" so it doesn't capture the wrong line.
    patterns: [
      /accounts receivable/i,
      /(?<!non[- ])trade (?:and other )?receivables/i,
      /(?<!non[- ])\breceivables\b/i,
    ],
  },
  {
    field: "debt",
    patterns: [
      /total (?:debt|borrowings)/i,
      /interest[- ]bearing (?:loans|borrowings)/i,
      /long[- ]term debt/i,
      /\bterm debt\b/i,
      /\bborrowings\b/i,
    ],
  },
  {
    field: "expenses",
    patterns: [
      /total operating expenses/i,
      /total expenses/i,
      /operating expenses/i,
      /administrative expenses/i,
      /\bopex\b/i,
    ],
  },
];

// Checked millions-before-thousands so a statement headed "(In millions, except
// number of shares, which are reflected in thousands)" is correctly read as
// millions — the thousands clause only applies to share counts, which we ignore.
const UNIT_SCALE: Array<{ pattern: RegExp; scale: number }> = [
  { pattern: /in billions|figures in billions|amounts in billions|billions of|nearest billion/i, scale: 1_000_000_000 },
  { pattern: /in millions|millions of|(?:aed|usd|us\$|\$|د\.إ)\s*['’]?\s*mn\b|(?:aed|usd|\$)\s*million|figures in millions|amounts in millions|\$ in millions|expressed in millions|nearest million/i, scale: 1_000_000 },
  // Match "AED'000", "AED 000", "AED ’000" (no space), "in thousands", etc.
  { pattern: /in '?000s?\b|in thousands|thousands of|(?:aed|usd|us\$|\$|د\.إ)\s*['’]?\s*0{3}\b|figures in thousands|amounts in thousands|expressed in thousands|nearest thousand/i, scale: 1_000 },
];

export function detectScale(text: string): number {
  // Search the whole focused window (already bounded to the statement pages, so
  // ~22k chars). The "in millions/thousands" note can appear on any statement
  // header, and its position shifts with page selection — searching all of it
  // makes scale detection stable.
  const head = text.slice(0, 40000);
  for (const { pattern, scale } of UNIT_SCALE) {
    if (pattern.test(head)) return scale;
  }
  return 1;
}

/** Best-effort currency detection from symbols / ISO codes in the statements. */
function detectCurrency(text: string): string | null {
  const head = text.slice(0, 6000);
  const checks: Array<[RegExp, string]> = [
    [/\bAED\b|د\.إ|dirham/i, "AED"],
    [/\bSAR\b|\briyal/i, "SAR"],
    [/\bEUR\b|€/, "EUR"],
    [/\bGBP\b|£/, "GBP"],
    [/\bINR\b|₹/, "INR"],
    [/\bUSD\b|US\$|\$/, "USD"],
  ];
  for (const [re, code] of checks) {
    if (re.test(head)) return code;
  }
  return null;
}

/**
 * Narrow a large filing (e.g. a 28-page 10-Q) down to the core financial
 * statements so both the LLM and the heuristic operate on the income statement,
 * balance sheet, and cash-flow statement rather than the whole document (cover
 * page dates, notes, MD&A — all sources of spurious numbers).
 */
export function selectStatementWindow(text: string, span = 16000): string {
  const anchors = [
    /statements? of operations/i,
    /statements? of income/i,
    /income statements?/i,
    /profit (?:and|&) loss/i,
    /statements? of comprehensive income/i,
    /balance sheets?/i,
    /statements? of financial position/i,
  ];
  let start = Number.POSITIVE_INFINITY;
  for (const re of anchors) {
    const m = re.exec(text);
    if (m && m.index < start) start = m.index;
  }
  if (!Number.isFinite(start)) return text.slice(0, 18000);
  return text.slice(start, start + span);
}

// Statement title patterns (IFRS + US GAAP + bank terminology).
const STATEMENT_TITLE =
  /(?:consolidated\s+|condensed\s+|interim\s+|group\s+)*(?:statements?\s+of\s+(?:operations|income|profit\s+or\s+loss|comprehensive\s+income|financial\s+position|cash\s*flows?|earnings)|balance\s+sheets?|income\s+statements?|profit\s+and\s+loss(?:\s+account)?)/i;

// Total / subtotal lines that appear in the body of a real statement (not a TOC).
const STATEMENT_BODY =
  /total\s+assets|total\s+liabilities|total\s+equity|total\s+current|net\s+(?:income|profit|loss|sales|revenue)|profit\s+for\s+the\s+(?:year|period)|(?:total\s+)?(?:operating\s+income|revenue|turnover)|cash\s+(?:generated|used|flows?|provided)[^.]{0,30}operating|total\s+comprehensive|net\s+interest\s+income|operating\s+expenses/gi;

const BIG_NUMBER = /\d{1,3}(?:,\d{3})+(?:\.\d+)?|\(\d{1,3}(?:,\d{3})+\)/g;

function countMatches(text: string, re: RegExp): number {
  const m = text.match(re);
  return m ? m.length : 0;
}

/**
 * Score each page for being an actual financial-statement table and return the
 * concatenated text of the best pages (in document order) plus their indices.
 *
 * This is the key fix for large filings: the financial statements in a 150-page
 * 10-K or a 99-page annual report are buried deep, and the FIRST textual mention
 * of "balance sheet" is almost always the table of contents or an MD&A sentence
 * — which contain no figures. Scoring by (title-as-heading + total-lines +
 * numeric density) finds the real statement pages instead.
 */
export function selectStatementText(
  pageTexts: string[],
  opts: { maxPages?: number; maxChars?: number } = {}
): { text: string; pageIndices: number[] } {
  const maxPages = opts.maxPages ?? 10;
  const maxChars = opts.maxChars ?? 22000;

  if (pageTexts.length <= 1) {
    const single = pageTexts[0] ?? "";
    return { text: selectStatementWindow(single, maxChars), pageIndices: [0] };
  }

  const scored = pageTexts.map((page, i) => {
    const head = page.slice(0, 600);
    let score = 0;
    if (STATEMENT_TITLE.test(head)) score += 6; // title as a heading near top
    else if (STATEMENT_TITLE.test(page)) score += 2; // title somewhere on page
    score += Math.min(countMatches(page, STATEMENT_BODY), 8) * 2;
    score += Math.min(countMatches(page, BIG_NUMBER), 40) * 0.25;
    // Table-of-contents / index pages have titles but no figures.
    if (/\bcontents\b|table of contents/i.test(head)) score -= 6;
    if (/\.{4,}\s*\d{1,3}\b/.test(page) && countMatches(page, BIG_NUMBER) < 6) score -= 4;
    return { i, score, len: page.length };
  });

  const ranked = scored.filter((s) => s.score >= 4).sort((a, b) => b.score - a.score);
  if (ranked.length === 0) {
    // Nothing scored as a statement — fall back to the whole-doc window.
    return { text: selectStatementWindow(pageTexts.join("\n"), 18000), pageIndices: [] };
  }

  const chosen = new Set<number>();

  // Guarantee at least the best page of EACH statement type (income, balance
  // sheet, cash flow) is included — otherwise a balance sheet that ranks below
  // several income-statement/MD&A pages can get cut from the window entirely.
  const CATEGORIES: RegExp[] = [
    /balance sheets?|statements? of financial position/i,
    /statements? of operations|statements? of income|income statements?|profit\s+or\s+loss|profit\s+and\s+loss/i,
    /statements? of cash\s*flows?/i,
  ];
  for (const cat of CATEGORIES) {
    let best: { i: number; score: number } | null = null;
    for (const s of scored) {
      if (cat.test(pageTexts[s.i].slice(0, 600)) && (!best || s.score > best.score)) {
        best = { i: s.i, score: s.score };
      }
    }
    if (best && best.score >= 2) chosen.add(best.i);
  }

  // Fill the rest with the top-scored pages.
  for (const s of ranked) {
    if (chosen.size >= maxPages) break;
    chosen.add(s.i);
  }
  // Include immediate continuation pages (statements spill onto the next page).
  for (const i of [...chosen]) {
    if (chosen.size < maxPages && pageTexts[i + 1]) chosen.add(i + 1);
  }
  const ordered = [...chosen].sort((a, b) => a - b);

  let text = "";
  const used: number[] = [];
  for (const idx of ordered) {
    if (text.length + pageTexts[idx].length > maxChars && text.length > 0) break;
    text += (text ? "\n\n" : "") + pageTexts[idx];
    used.push(idx);
  }
  return { text, pageIndices: used };
}

function dedupePreserveOrder(years: number[]): number[] {
  const ordered: number[] = [];
  const seen = new Set<number>();
  for (const y of years) {
    if (y >= 1990 && y <= 2100 && !seen.has(y)) {
      seen.add(y);
      ordered.push(y);
    }
  }
  if (ordered.length <= 4) return ordered;
  const topFour = new Set([...ordered].sort((a, b) => b - a).slice(0, 4));
  return ordered.filter((y) => topFour.has(y));
}

const MONTHS =
  "(?:jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)";

/**
 * Detect reporting-period years in column (appearance) order.
 *
 * Filings label columns with full dates ("December 27, 2025  December 28, 2024")
 * and are littered with unrelated years (footers like "Q1 2026", notes due
 * "2042"). So we prefer years that are part of a full date; only if none are
 * found do we fall back to bare 4-digit years on the densest year line.
 */
function detectYears(text: string): number[] {
  const dateYears = [
    ...text.matchAll(new RegExp(`${MONTHS}\\.?\\s+\\d{1,2},?\\s+((?:19|20)\\d{2})`, "gi")),
  ].map((m) => Number(m[1]));
  const fromDates = dedupePreserveOrder(dateYears);
  if (fromDates.length >= 1) return fromDates;

  // Fallback: the line carrying the most distinct bare years is the header row.
  const lines = text.split(/\r?\n/);
  let bestLine = "";
  let bestCount = 0;
  for (const l of lines) {
    const ys = l.match(/\b(?:19|20)\d{2}\b/g);
    const count = ys ? new Set(ys).size : 0;
    if (count > bestCount) {
      bestCount = count;
      bestLine = l;
    }
  }
  const source = bestCount >= 2 ? bestLine : text;
  const bare = (source.match(/\b(?:19|20)\d{2}\b/g) ?? []).map(Number);
  return dedupePreserveOrder(bare);
}

/**
 * Total debt is rarely a single line — it's the sum of current + non-current
 * term debt, commercial paper, notes payable, etc. Sum the components found in
 * the balance-sheet region (bounded before the cash-flow statement so financing
 * "repayments of term debt" lines are excluded). Returns one value per column.
 */
function sumDebtComponents(
  windowText: string,
  numColumns: number,
  scale: number,
  yearSet: Set<number>
): number[] | null {
  // Bound to the balance sheet: stop at the cash-flow statement.
  const cfIdx = /statements? of cash flows?/i.exec(windowText)?.index ?? windowText.length;
  const region = windowText.slice(0, cfIdx);

  // Prefer an explicit total-debt line if the issuer provides one.
  const totalRe = /\btotal (?:debt|borrowings)\b/i;
  const tm = totalRe.exec(region);
  const grab = (from: number): number[] => {
    const after = region.slice(from, from + 90);
    const nums = extractNumbers(after).filter((n) => !yearSet.has(n));
    return nums.slice(0, numColumns);
  };
  if (tm) {
    const nums = grab(tm.index + tm[0].length);
    if (nums.length) return nums.map((n) => n * scale);
  }

  const componentRe =
    /\b(?:long[- ]term debt|short[- ]term debt|term debt|commercial paper|notes payable|loans payable|bank (?:loans|borrowings)|borrowings)\b/gi;
  const sums = new Array(numColumns).fill(0);
  let found = 0;
  let m: RegExpExecArray | null;
  while ((m = componentRe.exec(region))) {
    const nums = grab(m.index + m[0].length);
    if (nums.length === 0) continue;
    nums.forEach((v, i) => {
      if (i < numColumns) sums[i] += Math.abs(v);
    });
    found++;
  }
  if (found === 0) return null;
  return sums.map((n) => n * scale);
}

/** Pull money-like number tokens from a line, honouring parentheses negatives. */
function extractNumbers(line: string): number[] {
  // Strip a leading label so embedded note references are less likely to leak.
  const tokens = line.match(/\(?\s*-?(?:AED|USD|US\$|\$|د\.إ)?\s*\d[\d,]*(?:\.\d+)?\s*\)?/gi) ?? [];
  const numbers: number[] = [];
  for (const tok of tokens) {
    const negative = /\(/.test(tok);
    const cleaned = tok.replace(/[(),\s]/g, "").replace(/[^0-9.\-]/g, "");
    if (!cleaned || cleaned === "-" || cleaned === ".") continue;
    const n = Number(cleaned);
    if (!Number.isFinite(n)) continue;
    // Drop tiny integers that are almost certainly note references.
    if (n < 100 && Number.isInteger(n) && !/\./.test(cleaned)) continue;
    numbers.push(negative ? -Math.abs(n) : n);
  }
  return numbers;
}

export function heuristicExtract(fullText: string): {
  records: FinancialRecordInput[];
  warnings: string[];
  companyName: string | null;
  currency: string | null;
} {
  const warnings: string[] = [];
  // Caller usually passes already-focused statement text (via selectStatementText).
  // Only re-window if it's a large raw document.
  const text = fullText.length > 24000 ? selectStatementWindow(fullText) : fullText;
  const scale = detectScale(text);
  if (scale > 1) {
    warnings.push(`Detected values stated in units of ${scale.toLocaleString()}; figures were scaled to absolute amounts.`);
  }

  // `yearsInOrder` follows the statement's column order (appearance order).
  let yearsInOrder = detectYears(text);
  if (yearsInOrder.length === 0) {
    // No year detected — assume a single most-recent fiscal year placeholder.
    yearsInOrder = [new Date().getFullYear() - 1];
    warnings.push("No fiscal year detected in the document — defaulted to one column. Please set the correct year.");
  }
  const yearSet = new Set(yearsInOrder);

  // Build records keyed by year so positional column mapping is unambiguous.
  const byYear = new Map<number, FinancialRecordInput>();
  for (const year of yearsInOrder) {
    byYear.set(year, {
      year,
      revenue: 0,
      netIncome: 0,
      totalAssets: 0,
      totalLiabilities: 0,
      equity: 0,
      cash: 0,
      operatingCashFlow: 0,
      receivables: 0,
      debt: 0,
      costOfGoodsSold: 0,
      expenses: 0,
    });
  }

  // PDF text extractors frequently collapse a statement onto one line with no
  // newlines, so a per-line scan fails. Instead we locate each label's position
  // in the full text and read the numbers that sit between it and the next
  // label — robust whether the text has line breaks or not.
  type LabelHit = { field: keyof Omit<FinancialRecordInput, "year">; start: number; end: number };
  const hits: LabelHit[] = [];
  for (const { field, patterns } of LINE_ITEM_ALIASES) {
    // Priority order: the FIRST pattern that matches wins (its earliest
    // occurrence), so a "Total ..." subtotal line beats the section header.
    for (const pattern of patterns) {
      const m = pattern.exec(text);
      if (m) {
        hits.push({ field, start: m.index, end: m.index + m[0].length });
        break;
      }
    }
  }

  // Sort by position so we can bound each label's number span by the next label.
  hits.sort((a, b) => a.start - b.start);
  const seen = new Set<string>();

  const numColumns = yearsInOrder.length;
  hits.forEach((hit, i) => {
    if (seen.has(hit.field)) return;
    const spanEnd = i + 1 < hits.length ? hits[i + 1].start : text.length;
    const span = text.slice(hit.end, spanEnd);
    let nums = extractNumbers(span);
    // Drop tokens that exactly equal a detected fiscal year (header bleed),
    // but only if doing so still leaves enough numbers for the columns.
    const withoutYears = nums.filter((n) => !yearSet.has(n));
    if (withoutYears.length >= numColumns) nums = withoutYears;
    if (nums.length === 0) return;

    // Column order == header (appearance) order, so the i-th number belongs to
    // the i-th detected year. Direct positional mapping — no reversal.
    nums.slice(0, numColumns).forEach((value, col) => {
      const year = yearsInOrder[col];
      const record = byYear.get(year);
      if (record) record[hit.field] = value * scale;
    });
    seen.add(hit.field);
  });

  if (seen.size === 0) {
    warnings.push("Could not locate any recognised financial line items. Please enter the figures manually below.");
  } else if (seen.size < 5) {
    warnings.push(`Only ${seen.size} financial line items were recognised automatically. Please review and complete the table below.`);
  }

  // Total debt = sum of all borrowing components (more accurate than the single
  // first-match captured in the main loop).
  const debtByColumn = sumDebtComponents(text, numColumns, scale, yearSet);
  if (debtByColumn) {
    debtByColumn.forEach((value, col) => {
      const record = byYear.get(yearsInOrder[col]);
      if (record && value > 0) record.debt = value;
    });
  }

  // Final records sorted ascending by year for clean display.
  const records = [...byYear.values()].sort((a, b) => a.year - b.year);

  // Costs are magnitudes: statements often print COGS/expenses in parentheses
  // (negative). The feature engine expects positive cost values.
  for (const r of records) {
    r.costOfGoodsSold = Math.abs(r.costOfGoodsSold);
    r.expenses = Math.abs(r.expenses);
  }

  // Detect a company name from the start of the FULL document (cover page),
  // capturing a phrase ending in a corporate-form suffix.
  const companyName = (() => {
    const head = fullText.slice(0, 1500);
    const m = head.match(
      /([A-Z][\w&.,'’\- ]*?\b(?:Inc\.?|Corp(?:oration)?\.?|LLC|FZE|FZ-LLC|FZCO|L\.L\.C\.?|Limited|Ltd\.?|PLC|PJSC|PSC|N\.V\.|S\.A\.|AG|Holdings|Group|Company|Co\.)\b)/
    );
    return m ? m[1].trim().replace(/\s+/g, " ").slice(0, 120) : null;
  })();

  // Currency is detected from the full document (the unit/currency note often
  // sits in the header above the statement title).
  return { records, warnings, companyName, currency: detectCurrency(fullText) };
}

/**
 * Main entry point: text -> structured records. Prefers the LLM, falls back to
 * the heuristic scanner. Always returns at least an (editable) skeleton.
 */
export async function extractFinancialsFromText(
  text: string
): Promise<ExtractionResult> {
  const trimmed = (text ?? "").trim();
  if (!trimmed) {
    return {
      records: [],
      warnings: [
        "No text layer found in the PDF. It may be a scanned image — OCR is not enabled in this MVP. Please upload a text-based PDF, CSV, or Excel file.",
      ],
      method: "pdf-heuristic",
      confidence: "low",
      companyName: null,
      currency: null,
    };
  }

  // Detect the unit scale once from the header and use it both to guide the LLM
  // (return figures as printed, we apply the multiplier) and the heuristic.
  const scale = detectScale(trimmed);

  // 1. LLM extraction (preferred when a key is set). `trimmed` is already the
  //    focused statement pages; only re-window a large raw document.
  const forLlm = trimmed.length > 22000 ? selectStatementWindow(trimmed, 20000) : trimmed;
  const llm = await extractFinancialsWithLlm(forLlm, scale);
  const llmRecon = llm ? reconcileRecords(llm.records).confidence : 0;

  // 2. Heuristic — always run (cheap) so we can cross-check the LLM. For
  //    well-structured US-GAAP statements the deterministic parser is often
  //    more reliable; for IFRS/bank layouts the LLM wins. Pick the better.
  const h = heuristicExtract(trimmed);
  const hRecon = h.records.length ? reconcileRecords(h.records).confidence : 0;

  const llmGood = !!llm && llm.records.length > 0;
  // Prefer the LLM when it reconciles well; otherwise take whichever is higher.
  const useLlm = llmGood && (llmRecon >= 0.8 || llmRecon >= hRecon);

  if (useLlm && llm) {
    return {
      records: llm.records,
      warnings: [
        "Figures were extracted by AI from the PDF. Please verify each value against the source document before running the analysis.",
        ...llm.notes,
      ],
      method: "pdf-llm",
      confidence: llmRecon >= 0.8 ? "high" : "medium",
      companyName: llm.companyName,
      currency: llm.currency,
    };
  }

  if (h.records.length > 0) {
    return {
      records: h.records,
      warnings: [
        llmGood
          ? "Figures were extracted by a rule-based parser (it reconciled better than the AI pass here). Review and correct the table below before analysis."
          : "Figures were extracted using a rule-based parser. Review and correct the table below before analysis.",
        ...h.warnings,
      ],
      method: "pdf-heuristic",
      confidence: hRecon >= 0.8 ? "high" : "low",
      companyName: h.companyName,
      currency: h.currency,
    };
  }

  // Nothing usable from either path.
  return {
    records: llm?.records ?? [],
    warnings: ["Could not extract financial figures from this document."],
    method: llmGood ? "pdf-llm" : "pdf-heuristic",
    confidence: "low",
    companyName: llm?.companyName ?? null,
    currency: llm?.currency ?? null,
  };
}
