"""PDF financial-statement extraction for the Python service (parity with the
Node/Vercel path).

Strategy:
  1. Extract text with pdfplumber.
  2. If OPENAI_API_KEY is set, ask the LLM to return structured records.
  3. Otherwise fall back to a heuristic label/number scanner.

The returned records use the same field names as ``FinancialRecordInput`` so the
existing inference pipeline can consume them directly.
"""

from __future__ import annotations

import io
import json
import os
import re
from typing import Dict, List, Optional, Tuple

import httpx

NUMERIC_FIELDS = [
    "revenue",
    "net_income",
    "total_assets",
    "total_liabilities",
    "equity",
    "cash",
    "operating_cash_flow",
    "receivables",
    "debt",
    "cost_of_goods_sold",
    "expenses",
]

# Label aliases tried in PRIORITY order (first match wins). "Total ..." subtotal
# lines precede the section headers they summarise, mirroring the Node parser.
LINE_ITEM_ALIASES: List[Tuple[str, List[str]]] = [
    ("cost_of_goods_sold", [r"total cost of sales", r"total cost of revenue", r"cost of goods sold", r"cost of sales", r"cost of revenue", r"\bcogs\b"]),
    ("operating_cash_flow", [
        r"cash generated by operating activities(?=\s*:?\s*\$?\s*[\d(])",
        r"net cash (?:generated|provided)(?: by)? operating activities(?=\s*:?\s*\$?\s*[\d(])",
        r"net cash (?:from|provided by|used in) operating activities(?=\s*:?\s*\$?\s*[\d(])",
        r"net cash (?:from|provided by|used in) operating",
        r"cash (?:flow )?from operations",
        r"operating cash flow",
        r"\bocf\b",
    ]),
    ("revenue", [r"total net sales", r"total revenue", r"total sales", r"net sales", r"\brevenue\b", r"\bturnover\b"]),
    ("net_income", [r"net income", r"net profit", r"profit for the (?:year|period)", r"(?:profit|loss) after tax", r"net earnings"]),
    ("total_assets", [r"total assets"]),
    ("total_liabilities", [r"total liabilities"]),
    ("equity", [r"total (?:shareholders|stockholders|owners)[’']? equity", r"total equity", r"shareholders[’']? equity"]),
    ("cash", [r"cash and cash equivalents", r"cash (?:&|and) equivalents", r"\bcash\b"]),
    ("receivables", [r"accounts receivable", r"(?<!non-)(?<!non )trade (?:and other )?receivables", r"(?<!non-)(?<!non )\breceivables\b"]),
    ("debt", [r"total (?:debt|borrowings)", r"interest[- ]bearing (?:loans|borrowings)", r"long[- ]term debt", r"\bterm debt\b", r"\bborrowings\b"]),
    ("expenses", [r"total operating expenses", r"total expenses", r"operating expenses", r"administrative expenses", r"\bopex\b"]),
]

# Checked billions -> millions -> thousands so "(In millions, except shares in
# thousands)" is correctly read as millions.
UNIT_SCALES = [
    (re.compile(r"in billions|figures in billions|amounts in billions|billions of|nearest billion", re.I), 1_000_000_000),
    (re.compile(r"in millions|millions of|(?:aed|usd|us\$|\$)\s*['’]?\s*mn\b|(?:aed|usd|\$)\s*million|figures in millions|amounts in millions|\$ in millions|expressed in millions|nearest million", re.I), 1_000_000),
    # Match "AED'000" / "AED ’000" (no space, common in UAE/IFRS filings), "in thousands", etc.
    (re.compile(r"in '?000s?\b|in thousands|thousands of|(?:aed|usd|us\$|\$)\s*['’]?\s*0{3}\b|figures in thousands|amounts in thousands|expressed in thousands|nearest thousand", re.I), 1_000),
]

MONTHS = (
    r"(?:jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|"
    r"aug(?:ust)?|sep(?:t(?:ember)?)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)"
)

STATEMENT_ANCHORS = [
    r"statements? of operations",
    r"statements? of income",
    r"income statements?",
    r"profit (?:and|&) loss",
    r"statements? of comprehensive income",
    r"balance sheets?",
    r"statements? of financial position",
]


def _select_statement_window(text: str, span: int = 16000) -> str:
    start = None
    for a in STATEMENT_ANCHORS:
        m = re.search(a, text, re.I)
        if m and (start is None or m.start() < start):
            start = m.start()
    if start is None:
        return text[:18000]
    return text[start:start + span]


_STMT_TITLE = re.compile(
    r"(?:consolidated\s+|condensed\s+|interim\s+|group\s+)*(?:statements?\s+of\s+(?:operations|income|profit\s+or\s+loss|comprehensive\s+income|financial\s+position|cash\s*flows?|earnings)|balance\s+sheets?|income\s+statements?|profit\s+and\s+loss(?:\s+account)?)",
    re.I,
)
_STMT_BODY = re.compile(
    r"total\s+assets|total\s+liabilities|total\s+equity|total\s+current|net\s+(?:income|profit|loss|sales|revenue)|profit\s+for\s+the\s+(?:year|period)|operating\s+income|revenue|turnover|cash\s+(?:generated|used|flows?|provided)|net\s+interest\s+income",
    re.I,
)
_BIG_NUM = re.compile(r"\d{1,3}(?:,\d{3})+(?:\.\d+)?|\(\d{1,3}(?:,\d{3})+\)")


def _select_statement_text(page_texts: List[str], max_pages: int = 10, max_chars: int = 18000) -> str:
    """Page-aware: score each page and concatenate the real statement pages.
    In a large filing the first mention of 'balance sheet' is the table of
    contents/MD&A (no numbers); scoring finds the actual statement tables."""
    if len(page_texts) <= 1:
        return _select_statement_window(page_texts[0] if page_texts else "", max_chars)

    scored = []
    for i, page in enumerate(page_texts):
        head = page[:600]
        score = 0.0
        if _STMT_TITLE.search(head):
            score += 6
        elif _STMT_TITLE.search(page):
            score += 2
        score += min(len(_STMT_BODY.findall(page)), 8) * 2
        score += min(len(_BIG_NUM.findall(page)), 40) * 0.25
        if re.search(r"\bcontents\b|table of contents", head, re.I):
            score -= 6
        if re.search(r"\.{4,}\s*\d{1,3}\b", page) and len(_BIG_NUM.findall(page)) < 6:
            score -= 4
        scored.append((i, score))

    ranked = sorted([s for s in scored if s[1] >= 4], key=lambda s: -s[1])
    if not ranked:
        return _select_statement_window("\n".join(page_texts), 18000)
    chosen = set(i for i, _ in ranked[:max_pages])
    for i, _ in ranked[:max_pages]:
        if len(chosen) < max_pages and i + 1 < len(page_texts):
            chosen.add(i + 1)
    out = ""
    for idx in sorted(chosen):
        if out and len(out) + len(page_texts[idx]) > max_chars:
            break
        out += ("\n\n" if out else "") + page_texts[idx]
    return out


def _detect_currency(text: str):
    head = text[:6000]
    for pattern, code in [
        (r"\bAED\b|dirham", "AED"),
        (r"\bSAR\b|riyal", "SAR"),
        (r"\bEUR\b|€", "EUR"),
        (r"\bGBP\b|£", "GBP"),
        (r"\bUSD\b|US\$|\$", "USD"),
    ]:
        if re.search(pattern, head, re.I):
            return code
    return None


def extract_pdf_text(raw: bytes) -> Tuple[str, int]:
    """Return (text, page_count). Empty text means no extractable layer."""
    try:
        import pdfplumber  # imported lazily so the service starts without it
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(f"pdfplumber not installed: {exc}")

    chunks: List[str] = []
    pages = 0
    with pdfplumber.open(io.BytesIO(raw)) as pdf:
        pages = len(pdf.pages)
        for page in pdf.pages:
            chunks.append(page.extract_text() or "")
    return "\n".join(chunks), pages


def extract_pdf_page_texts(raw: bytes) -> List[str]:
    """Per-page text, used for page-aware statement selection on large filings."""
    try:
        import pdfplumber
    except Exception as exc:  # noqa: BLE001
        raise RuntimeError(f"pdfplumber not installed: {exc}")
    out: List[str] = []
    with pdfplumber.open(io.BytesIO(raw)) as pdf:
        for page in pdf.pages:
            out.append(page.extract_text() or "")
    return out


def _detect_scale(text: str) -> int:
    head = text[:2000]
    for pattern, scale in UNIT_SCALES:
        if pattern.search(head):
            return scale
    return 1


def _dedupe_years(years: List[int]) -> List[int]:
    ordered: List[int] = []
    seen = set()
    for y in years:
        if 1990 <= y <= 2100 and y not in seen:
            seen.add(y)
            ordered.append(y)
    if len(ordered) <= 4:
        return ordered
    top_four = set(sorted(ordered, reverse=True)[:4])
    return [y for y in ordered if y in top_four]


def _detect_years(text: str) -> List[int]:
    """Prefer years that are part of a full date (column headers); fall back to
    bare years on the densest line. Avoids footer years like 'Q1 2026'."""
    date_years = [int(m) for m in re.findall(MONTHS + r"\.?\s+\d{1,2},?\s+((?:19|20)\d{2})", text, re.I)]
    from_dates = _dedupe_years(date_years)
    if from_dates:
        return from_dates

    best_line, best_count = "", 0
    for line in text.splitlines():
        ys = re.findall(r"\b(?:19|20)\d{2}\b", line)
        if len(set(ys)) > best_count:
            best_count = len(set(ys))
            best_line = line
    source = best_line if best_count >= 2 else text
    bare = [int(y) for y in re.findall(r"\b(?:19|20)\d{2}\b", source)]
    return _dedupe_years(bare)


def _extract_numbers(line: str) -> List[float]:
    tokens = re.findall(r"\(?\s*-?(?:AED|USD|US\$|\$)?\s*\d[\d,]*(?:\.\d+)?\s*\)?", line, re.I)
    numbers: List[float] = []
    for tok in tokens:
        negative = "(" in tok
        cleaned = re.sub(r"[(),\s]", "", tok)
        cleaned = re.sub(r"[^0-9.\-]", "", cleaned)
        if not cleaned or cleaned in {"-", "."}:
            continue
        try:
            n = float(cleaned)
        except ValueError:
            continue
        if n < 100 and float(n).is_integer() and "." not in cleaned:
            continue  # likely a note reference
        numbers.append(-abs(n) if negative else n)
    return numbers


def _sum_debt_components(window: str, num_columns: int, scale: float, year_set: set):
    """Total debt = sum of all borrowing components in the balance-sheet region."""
    cf = re.search(r"statements? of cash flows?", window, re.I)
    region = window[: cf.start()] if cf else window

    def grab(pos: int) -> List[float]:
        nums = [n for n in _extract_numbers(region[pos:pos + 90]) if int(n) not in year_set]
        return nums[:num_columns]

    tm = re.search(r"\btotal (?:debt|borrowings)\b", region, re.I)
    if tm:
        nums = grab(tm.end())
        if nums:
            return [n * scale for n in nums]

    sums = [0.0] * num_columns
    found = 0
    comp = re.compile(
        r"\b(?:long[- ]term debt|short[- ]term debt|term debt|commercial paper|notes payable|loans payable|bank (?:loans|borrowings)|borrowings)\b",
        re.I,
    )
    for m in comp.finditer(region):
        nums = grab(m.end())
        if not nums:
            continue
        for i, v in enumerate(nums):
            if i < num_columns:
                sums[i] += abs(v)
        found += 1
    if found == 0:
        return None
    return [n * scale for n in sums]


def heuristic_extract(full_text: str) -> Tuple[List[Dict], List[str]]:
    warnings: List[str] = []
    # Focus on the core financial statements.
    text = _select_statement_window(full_text)
    scale = _detect_scale(text)
    if scale > 1:
        warnings.append(f"Values detected in units of {scale:,}; scaled to absolute amounts.")

    years = _detect_years(text)
    if not years:
        from datetime import datetime

        years = [datetime.utcnow().year - 1]
        warnings.append("No fiscal year detected; defaulted to one column. Set the correct year.")

    year_set = set(years)
    num_columns = len(years)
    by_year = {y: {"year": y, **{f: 0.0 for f in NUMERIC_FIELDS}} for y in years}

    # Priority-order matching: the FIRST pattern that matches wins (its earliest
    # occurrence), so "Total ..." subtotal lines beat section headers.
    hits = []  # (field, start, end)
    for field, patterns in LINE_ITEM_ALIASES:
        for p in patterns:
            m = re.search(p, text, re.I)
            if m:
                hits.append((field, m.start(), m.end()))
                break
    hits.sort(key=lambda h: h[1])

    seen = set()
    for i, (field, _start, end) in enumerate(hits):
        if field in seen:
            continue
        span_end = hits[i + 1][1] if i + 1 < len(hits) else len(text)
        span = text[end:span_end]
        nums = _extract_numbers(span)
        without_years = [n for n in nums if int(n) not in year_set]
        if len(without_years) >= num_columns:
            nums = without_years
        if not nums:
            continue
        # Column order == header order: i-th number -> i-th detected year.
        for col, value in enumerate(nums[:num_columns]):
            by_year[years[col]][field] = value * scale
        seen.add(field)

    if not seen:
        warnings.append("No recognised financial line items found. Manual entry required.")
    elif len(seen) < 5:
        warnings.append(f"Only {len(seen)} line items recognised automatically; please review.")

    debt_by_col = _sum_debt_components(text, num_columns, scale, year_set)
    if debt_by_col:
        for col, value in enumerate(debt_by_col):
            if value > 0:
                by_year[years[col]]["debt"] = value

    records = [by_year[y] for y in sorted(by_year)]
    for r in records:
        r["cost_of_goods_sold"] = abs(r["cost_of_goods_sold"])
        r["expenses"] = abs(r["expenses"])
    return records, warnings


def llm_extract(text: str) -> Optional[Tuple[List[Dict], Optional[str], Optional[str], List[str]]]:
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        return None

    base = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    model = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
    snippet = text[:16000]

    system = (
        "You are a precise financial-statement data-extraction engine. Return STRICT JSON. "
        "Never invent figures — use 0 when not found. Output ABSOLUTE currency units: 'in "
        "millions' => multiply by 1,000,000; 'in thousands' => 1,000 (the 'except shares in "
        "thousands' note applies only to share counts, which you ignore). Use negatives for "
        "losses and cash outflows (parentheses)."
    )
    user = (
        "Return JSON: {\"companyName\": string|null, \"currency\": string|null, "
        "\"records\": [{\"year\": number, \"revenue\": number, \"net_income\": number, "
        "\"total_assets\": number, \"total_liabilities\": number, \"equity\": number, \"cash\": number, "
        "\"operating_cash_flow\": number, \"receivables\": number, \"debt\": number, "
        "\"cost_of_goods_sold\": number, \"expenses\": number}], \"notes\": string[]}\n\n"
        "Produce ONE record per reporting PERIOD (column), combining the income statement, "
        "balance sheet, and cash-flow statement for that period. Output at most the 2 most "
        "recent periods; use the period-END date's calendar year as `year` (offset the older "
        "one by -1 if both share a year). Use TOTAL/subtotal lines (total net sales, total cost "
        "of sales, total operating expenses). debt = SUM of all borrowings (short + long term + "
        "term debt + commercial paper + notes payable). cash = cash and cash equivalents only. "
        "receivables = trade/accounts receivable (not vendor non-trade). costOfGoodsSold and "
        "expenses are positive.\n\n"
        f"FINANCIAL STATEMENTS TEXT:\n```\n{snippet}\n```"
    )

    try:
        with httpx.Client(timeout=30.0) as client:
            res = client.post(
                f"{base}/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={
                    "model": model,
                    "messages": [
                        {"role": "system", "content": system},
                        {"role": "user", "content": user},
                    ],
                    "temperature": 0,
                    "max_tokens": 1500,
                    "response_format": {"type": "json_object"},
                },
            )
            res.raise_for_status()
            content = res.json()["choices"][0]["message"]["content"]
            parsed = json.loads(content)
    except Exception as exc:  # noqa: BLE001
        print(f"[WARN] LLM PDF extraction failed: {exc}")
        return None

    raw_records = parsed.get("records", [])
    records: List[Dict] = []
    for item in raw_records:
        try:
            year = int(round(float(item.get("year", 0))))
        except (TypeError, ValueError):
            continue
        if not (1990 <= year <= 2100):
            continue
        rec = {"year": year}
        for f in NUMERIC_FIELDS:
            try:
                rec[f] = float(item.get(f, 0) or 0)
            except (TypeError, ValueError):
                rec[f] = 0.0
        # Costs are magnitudes regardless of statement sign convention.
        rec["cost_of_goods_sold"] = abs(rec["cost_of_goods_sold"])
        rec["expenses"] = abs(rec["expenses"])
        records.append(rec)

    if not records:
        return None
    notes = parsed.get("notes", []) if isinstance(parsed.get("notes"), list) else []
    return records, parsed.get("companyName"), parsed.get("currency"), notes


def vision_extract(raw: bytes) -> Optional[Tuple[List[Dict], Optional[str], Optional[str], List[str]]]:
    """Send the PDF directly to an OpenAI vision model (native PDF input → OCR).
    Works for scanned / image-only PDFs without a local Tesseract dependency."""
    api_key = os.environ.get("OPENAI_API_KEY", "").strip()
    if not api_key:
        return None
    if len(raw) > 8 * 1024 * 1024:
        return None

    import base64

    base = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    model = os.environ.get("OPENAI_VISION_MODEL") or os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
    data_url = "data:application/pdf;base64," + base64.b64encode(raw).decode()

    instruction = (
        "You are a precise financial-statement data-extraction engine reading a company filing "
        "(it may be a scanned image). Read the income statement, balance sheet, and cash-flow "
        "statement. Output ABSOLUTE units ('in millions' => x1,000,000; 'in thousands' => x1,000; "
        "'except shares in thousands' applies only to share counts). Parentheses are negative. "
        'Return STRICT JSON {"companyName": string|null, "currency": string|null, "records": '
        '[{"year": number, "revenue": number, "net_income": number, "total_assets": number, '
        '"total_liabilities": number, "equity": number, "cash": number, "operating_cash_flow": '
        'number, "receivables": number, "debt": number, "cost_of_goods_sold": number, "expenses": '
        'number}], "notes": string[]}. One record per reporting period (max 2 most recent); year = '
        "period-end year. Use TOTAL lines. debt = sum of all borrowings. Balance sheet must satisfy "
        "assets = liabilities + equity."
    )

    try:
        with httpx.Client(timeout=90.0) as client:
            res = client.post(
                f"{base}/chat/completions",
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
                json={
                    "model": model,
                    "messages": [{
                        "role": "user",
                        "content": [
                            {"type": "text", "text": instruction},
                            {"type": "file", "file": {"filename": "filing.pdf", "file_data": data_url}},
                        ],
                    }],
                    "temperature": 0,
                    "max_tokens": 1600,
                    "response_format": {"type": "json_object"},
                },
            )
            res.raise_for_status()
            parsed = json.loads(res.json()["choices"][0]["message"]["content"])
    except Exception as exc:  # noqa: BLE001
        print(f"[WARN] Vision extraction failed: {exc}")
        return None

    records: List[Dict] = []
    for item in parsed.get("records", []):
        try:
            year = int(round(float(item.get("year", 0))))
        except (TypeError, ValueError):
            continue
        if not (1990 <= year <= 2100):
            continue
        rec = {"year": year}
        for f in NUMERIC_FIELDS:
            try:
                rec[f] = float(item.get(f, 0) or 0)
            except (TypeError, ValueError):
                rec[f] = 0.0
        rec["cost_of_goods_sold"] = abs(rec["cost_of_goods_sold"])
        rec["expenses"] = abs(rec["expenses"])
        records.append(rec)
    if not records:
        return None
    notes = parsed.get("notes", []) if isinstance(parsed.get("notes"), list) else []
    return records, parsed.get("companyName"), parsed.get("currency"), notes


def extract_financials_from_pdf(
    raw: bytes,
) -> Tuple[List[Dict], List[str], str, Optional[str], Optional[str]]:
    """Return (records, warnings, method, detected_company_name, currency)."""
    page_texts = extract_pdf_page_texts(raw)
    text = "\n".join(page_texts)

    # Scanned / image-only PDF (no text layer) → vision OCR.
    if not text.strip():
        vision = vision_extract(raw)
        if vision is not None:
            records, company, currency, notes = vision
            return records, [
                "Figures read directly from the PDF by the vision model (OCR). Verify against the source.",
                *notes,
            ], "pdf-vision", company, currency
        return [], ["No text layer found (scanned image). Configure OPENAI_API_KEY for OCR."], "pdf-empty", None, None

    # Page-aware: feed the LLM the actual statement pages, not the table of contents.
    window = _select_statement_text(page_texts)
    llm = llm_extract(window)
    if llm is not None:
        records, company, currency, notes = llm
        warnings = [
            "Figures extracted by AI from the PDF — verify against the source before relying on them.",
            *notes,
        ]
        return records, warnings, "pdf-llm", company, currency

    records, warnings = heuristic_extract(window)
    warnings.insert(0, "Figures extracted by a rule-based parser (no AI key). Review carefully.")
    return records, warnings, "pdf-heuristic", None, _detect_currency(text)
